name: trivy-iac-scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    name: Aqua Trivy IaC Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate SARIF Results
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: config
          scan-ref: .
          format: sarif
          output: trivy-results.sarif
          exit-code: '0'

      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif

      - name: Fail on IaC Misconfigurations
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: config
          scan-ref: .
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL